### ISSUE TITLE
"Couldn't verify getsubids command, do you have installed and updated getsubids/shadow package?" 

### ISSUE THREAD

**Issue by Egless3** [alvr-org/ALVR-Distrobox-Linux-Guide#20] opened 2024-01-02 21:56 UTC
./setup-phase-1-2.sh: line 115: getsubids: command not found
 : Couldn't verify getsubids command, do you have installed and updated getsubids/shadow package?

the "newgidmap" command is available.
"uidmap" is installed. 

Linux Mint 21.2 x86_64 (KDE Plasma 5.24.7)

**Comment by DePingus** [comment] 2024-01-03 07:25
I'm on Fedora 39 and have a similar error about `getsubids`.

```
 : Phase 1
 : You don't seem to have getsubids command, i will use whipped one instead
 : But considering this fact, things might not work correctly for your distribution
 : Installing lilipod
```

The script continues and then tries to to download `lilipod` from the internet. But then next error then becomes:

```
mkdir: cannot create directory ‘/home/depingus/repos/ALVR-Distrobox-Linux-Guide/installation-lilipod/bin’: File exists

```



I clearly have it installed.

```
depingus@XXXXXXX ~/r/ALVR-Distrobox-Linux-Guide> getsubids
Usage: getsubids [-g] user
    list subuid ranges for user
    pass -g to list subgid ranges
````
I tried installing `shaodw-utils` anyways and `dnf` confirmed it was already installed.

TBH, I hate everything about this install process. When I tried the `uninstall.sh` script it asked for the sudo password even though the `setup.sh` script didn't (at least up to the point it got) and then downloaded another script from the internet to run. That is just not cool.

**Comment by Meister1593** [comment] 2024-01-03 07:57
> I'm on Fedora 39 and have a similar error about `getsubids`.
> 
> ```
>  : Phase 1
>  : You don't seem to have getsubids command, i will use whipped one instead
>  : But considering this fact, things might not work correctly for your distribution
>  : Installing lilipod
> ```
> 
> The script continues and then tries to to download `lilipod` from the internet. But then next error then becomes:
> 
> ```
> mkdir: cannot create directory ‘/home/depingus/repos/ALVR-Distrobox-Linux-Guide/installation-lilipod/bin’: File exists
> ```
> 
> I clearly have it installed.
> 
> ```
> depingus@XXXXXXX ~/r/ALVR-Distrobox-Linux-Guide> getsubids
> Usage: getsubids [-g] user
>     list subuid ranges for user
>     pass -g to list subgid ranges
> ```
> 
> I tried installing `shaodw-utils` anyways and `dnf` confirmed it was already installed.
> 
> TBH, I hate everything about this install process. When I tried the `uninstall.sh` script it asked for the sudo password even though the `setup.sh` script didn't (at least up to the point it got) and then downloaded another script from the internet to run. That is just not cool.

Hello
I'm sorry to hear that you hate this installation method, you seem to have collected a lot of issues along the way while i was still in process of testing it (before it was almost completely non-functional after many updates from other side)
Can you provide setup.log from installation just in case?
As for sudo, it is required because apparently libpod creates files by user, that you cannot delete normally without superuser.

**Comment by Meister1593** [comment] 2024-01-03 08:02
I updated repository with latest changes, it shouldn't use shipped getsubids now if it works properly.
As for @Egless3, try using it again as well, uidmap on mint doesn't contain getsubids so it will use shipped one.

**Comment by DePingus** [comment] 2024-01-03 10:20
Wow. I did not expect such a quick reply. I should apologize for that "hate" comment. That was way too strong a word.  I'm sorry and I hope I didn't bum you out too much. This is a great project and the last thing I want is to put it down.

I still take some issue with internet scripts invoking sudo and then calling other internet scripts. But I understand and I don't think you're being nefarious here. It's just the nature of some installs.

Sorry I wiped everything so I don't have the crashing setup.log for you. But I went ahead and tested out your update and now the `setup.sh` install script installs without issues. I really appreciate the work you put in there. As I hoped, it runs WAY better than the appimage. This was a huge improvement for me. Thank you so much! If you need any more info from me, just ask.

**Comment by Meister1593** [comment] 2024-01-03 10:23
> Wow. I did not expect such a quick reply. I should apologize for that "hate" comment. That was way too strong a word. I'm sorry and I hope I didn't bum you out too much. This is a great project and the last thing I want is to put it down.
> 
> I still take some issue with internet scripts invoking sudo and then calling other internet scripts. But I understand and I don't think you're being nefarious here. It's just the nature of some installs.
> 
> Sorry I wiped everything so I don't have the crashing setup.log for you. But I went ahead and tested out your update and now the `setup.sh` install script installs without issues. I really appreciate the work you put in there. As I hoped, it runs WAY better than the appimage. This was a huge improvement for me. Thank you so much! If you need any more info from me, just ask.

Glad to hear everything worked! Thank you for feedback.

**Comment by DePingus** [comment] 2024-01-03 10:27
I'm not OP so I can't close this. But again, much appreciated.

**Comment by Egless3** [comment] 2024-01-03 17:08
> I updated repository with latest changes, it shouldn't use shipped getsubids now if it works properly. As for @Egless3, try using it again as well, uidmap on mint doesn't contain getsubids so it will use shipped one.

Reinstalled and am no longer getting the "getsubids" error. However now I'm getting a Error titled "Couldn't install distrobox container first time at phase 3..." 


Setup.log found bellow
[setup.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/13821569/setup.log)

**Comment by Meister1593** [comment] 2024-01-03 18:03
> > I updated repository with latest changes, it shouldn't use shipped getsubids now if it works properly. As for @Egless3, try using it again as well, uidmap on mint doesn't contain getsubids so it will use shipped one.
> 
> Reinstalled and am no longer getting the "getsubids" error. However now I'm getting a Error titled "Couldn't install distrobox container first time at phase 3..."
> 
> Setup.log found bellow [setup.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/13821569/setup.log)

I'm pretty sure it's same bug as here https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/issues/13 ...

**Comment by Meister1593** [comment] 2024-01-03 18:11
> > I updated repository with latest changes, it shouldn't use shipped getsubids now if it works properly. As for @Egless3, try using it again as well, uidmap on mint doesn't contain getsubids so it will use shipped one.
> 
> Reinstalled and am no longer getting the "getsubids" error. However now I'm getting a Error titled "Couldn't install distrobox container first time at phase 3..."
> 
> Setup.log found bellow [setup.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/13821569/setup.log)

Can i ask you nvidia driver version? i feel like i notice a pattern there

**Comment by Egless3** [comment] 2024-01-03 19:19
> > > I updated repository with latest changes, it shouldn't use shipped getsubids now if it works properly. As for @Egless3, try using it again as well, uidmap on mint doesn't contain getsubids so it will use shipped one.
> > 
> > 
> > Reinstalled and am no longer getting the "getsubids" error. However now I'm getting a Error titled "Couldn't install distrobox container first time at phase 3..."
> > Setup.log found bellow [setup.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/13821569/setup.log)
> 
> Can i ask you nvidia driver version? i feel like i notice a pattern there

Nvidia-driver-535
Version 535.129.03-0ubuntu0.22.04.1
NVIDIA driver metapackage

**Comment by Meister1593** [comment] 2024-01-03 19:21
Oh okay, this looks fine... another user had 470 driver which wouldn't have worked at all with alvr anyway.

Okay then, i might need to take a look at distrobox codebase to see what's wrong exactly...

**Comment by Egless3** [comment] 2024-01-03 19:48
> > > I updated repository with latest changes, it shouldn't use shipped getsubids now if it works properly. As for @Egless3, try using it again as well, uidmap on mint doesn't contain getsubids so it will use shipped one.
> > 
> > 
> > Reinstalled and am no longer getting the "getsubids" error. However now I'm getting a Error titled "Couldn't install distrobox container first time at phase 3..."
> > Setup.log found bellow [setup.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/13821569/setup.log)
> 
> I'm pretty sure it's same bug as here #13 ...

Went to this article and attempted to edit my setup-phase-1-2.sh file to include the --verbose statement, but it appears line 134 no longer contains the statement that would need to be changed. line 134 now reads as "phase1_lilipod_distrobox_install"

**Comment by Meister1593** [comment] 2024-01-03 19:58
> > > > I updated repository with latest changes, it shouldn't use shipped getsubids now if it works properly. As for @Egless3, try using it again as well, uidmap on mint doesn't contain getsubids so it will use shipped one.
> > > 
> > > 
> > > Reinstalled and am no longer getting the "getsubids" error. However now I'm getting a Error titled "Couldn't install distrobox container first time at phase 3..."
> > > Setup.log found bellow [setup.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/13821569/setup.log)
> > 
> > 
> > I'm pretty sure it's same bug as here #13 ...
> 
> Went to this article and attempted to edit my setup-phase-1-2.sh file to include the --verbose statement, but it appears line 134 no longer contains the statement that would need to be changed. line 134 now reads as "phase1_lilipod_distrobox_install"

It's probably unnecessary as i'm 90% sure it's same issue, but if you really want to - you can change it on 92 line instead

**Comment by Egless3** [comment] 2024-01-05 02:29
> > > > > I updated repository with latest changes, it shouldn't use shipped getsubids now if it works properly. As for @Egless3, try using it again as well, uidmap on mint doesn't contain getsubids so it will use shipped one.
> > > > 
> > > > 
> > > > Reinstalled and am no longer getting the "getsubids" error. However now I'm getting a Error titled "Couldn't install distrobox container first time at phase 3..."
> > > > Setup.log found bellow [setup.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/13821569/setup.log)
> > > 
> > > 
> > > I'm pretty sure it's same bug as here #13 ...
> > 
> > 
> > Went to this article and attempted to edit my setup-phase-1-2.sh file to include the --verbose statement, but it appears line 134 no longer contains the statement that would need to be changed. line 134 now reads as "phase1_lilipod_distrobox_install"
> 
> It's probably unnecessary as i'm 90% sure it's same issue, but if you really want to - you can change it on 92 line instead

I only just now got the chance to fully read through that mentioned forum post, am i just kinda boned until a future update?

**Comment by Meister1593** [comment] 2024-01-06 14:16
Possibly... i would try going with appimage way for now, until this gets resolved.

Maybe i will also fix the issue with dashboard not showing up by then

**Comment by Meister1593** [comment] 2024-01-06 14:17
I will close this issue as it's not related to og one anymore, but feel free to write up or subscribe to #13 to make sure it is tracked for you

**Closed as completed by Meister1593** 2024-01-06 14:17 UTC
